version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      gomod:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
