package githubapp

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/go-github/v75/github"
)

type fixRunResult struct {
	ExitCode int
	Stdout   string
	Stderr   string
	Changed  bool
	Branch   string
}

func (service *Service) processIssueComment(event *github.IssueCommentEvent, installationID int64, command FixCommand) {
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Minute)
	defer cancel()

	owner := ownerFromRepository(event.GetRepo())
	repo := event.GetRepo().GetName()
	defaultBranch := event.GetRepo().GetDefaultBranch()
	issueNumber := event.GetIssue().GetNumber()

	client, token, err := service.installationClient(ctx, installationID)
	if err != nil {
		service.logger.Printf("issue_comment %s/%s: install client: %v", owner, repo, err)
		return
	}

	service.postIssueComment(ctx, client, owner, repo, issueNumber, "PatchPilot started remediation with `cvefix fix`.")

	result, err := service.runFixWorkflow(ctx, owner, repo, defaultBranch, token, command)
	if err != nil {
		service.postIssueComment(ctx, client, owner, repo, issueNumber, fmt.Sprintf("PatchPilot remediation failed: %v", err))
		return
	}

	if !result.Changed {
		message := fmt.Sprintf("PatchPilot finished. No file changes were needed (cvefix exit code `%d`).", result.ExitCode)
		service.postIssueComment(ctx, client, owner, repo, issueNumber, message)
		return
	}

	pr, _, err := client.PullRequests.Create(ctx, owner, repo, &github.NewPullRequest{
		Title: github.String("chore: automated CVE remediation"),
		Head:  github.String(result.Branch),
		Base:  github.String(defaultBranch),
		Body: github.String(fmt.Sprintf(
			"Automated remediation generated by PatchPilot App.\n\n- Trigger: issue comment by @%s\n- Command: `%s`\n- cvefix exit code: `%d`\n\nStdout (truncated):\n```text\n%s\n```\n\nStderr (truncated):\n```text\n%s\n```",
			event.GetSender().GetLogin(),
			"/cvefix fix",
			result.ExitCode,
			truncateForComment(result.Stdout),
			truncateForComment(result.Stderr),
		)),
	})
	if err != nil {
		service.postIssueComment(ctx, client, owner, repo, issueNumber, fmt.Sprintf("PatchPilot applied changes but failed to create PR: %v", err))
		return
	}

	message := fmt.Sprintf("PatchPilot opened remediation PR: %s", pr.GetHTMLURL())
	if command.AutoMerge {
		message += "\n\n`--auto-merge` was requested. Auto-merge policy is enforced by repository settings once checks pass."
	}
	service.postIssueComment(ctx, client, owner, repo, issueNumber, message)
}

func (service *Service) processPushEvent(event *github.PushEvent, installationID int64) {
	ctx, cancel := context.WithTimeout(context.Background(), 20*time.Minute)
	defer cancel()

	owner := ownerFromPushRepository(event.GetRepo())
	repo := event.GetRepo().GetName()
	defaultBranch := event.GetRepo().GetDefaultBranch()

	client, token, err := service.installationClient(ctx, installationID)
	if err != nil {
		service.logger.Printf("push %s/%s: install client: %v", owner, repo, err)
		return
	}

	result, err := service.runFixWorkflow(ctx, owner, repo, defaultBranch, token, FixCommand{})
	if err != nil {
		service.logger.Printf("push remediation failed for %s/%s: %v", owner, repo, err)
		return
	}
	if !result.Changed {
		service.logger.Printf("push remediation found no changes for %s/%s (exit=%d)", owner, repo, result.ExitCode)
		return
	}

	pr, _, err := client.PullRequests.Create(ctx, owner, repo, &github.NewPullRequest{
		Title: github.String("chore: automated CVE remediation"),
		Head:  github.String(result.Branch),
		Base:  github.String(defaultBranch),
		Body: github.String(fmt.Sprintf(
			"Automated remediation generated by PatchPilot App on push to `%s`.",
			defaultBranch,
		)),
	})
	if err != nil {
		service.logger.Printf("push remediation applied changes for %s/%s but PR creation failed: %v", owner, repo, err)
		return
	}

	service.logger.Printf("push remediation opened PR %s for %s/%s", pr.GetHTMLURL(), owner, repo)
}

func ownerFromRepository(repo *github.Repository) string {
	if repo == nil || repo.Owner == nil {
		return ""
	}
	owner := strings.TrimSpace(repo.GetOwner().GetLogin())
	if owner != "" {
		return owner
	}
	return strings.TrimSpace(repo.GetOwner().GetName())
}

func ownerFromPushRepository(repo *github.PushEventRepository) string {
	if repo == nil || repo.Owner == nil {
		return ""
	}
	owner := strings.TrimSpace(repo.GetOwner().GetLogin())
	if owner != "" {
		return owner
	}
	return strings.TrimSpace(repo.GetOwner().GetName())
}

func (service *Service) runFixWorkflow(ctx context.Context, owner, repo, defaultBranch, token string, command FixCommand) (fixRunResult, error) {
	if strings.TrimSpace(owner) == "" || strings.TrimSpace(repo) == "" {
		return fixRunResult{}, fmt.Errorf("owner and repo must not be empty")
	}
	if strings.TrimSpace(defaultBranch) == "" {
		defaultBranch = "master"
	}

	tempRoot, err := os.MkdirTemp(service.cfg.WorkDir, "patchpilot-repo-")
	if err != nil {
		return fixRunResult{}, fmt.Errorf("create temp dir: %w", err)
	}
	defer os.RemoveAll(tempRoot)

	repoPath := filepath.Join(tempRoot, "repo")
	cloneURL, err := repositoryCloneURL(service.cfg.GitHubBaseWebURL, owner, repo, token)
	if err != nil {
		return fixRunResult{}, err
	}

	if _, _, err := runCommand(ctx, tempRoot, nil, "git", "clone", "--depth", "1", "--branch", defaultBranch, cloneURL, repoPath); err != nil {
		return fixRunResult{}, fmt.Errorf("clone repository: %w", err)
	}

	args := []string{"fix", "--dir", repoPath, "--enable-agent=false"}
	if strings.TrimSpace(command.PolicyPath) != "" {
		policyPath := command.PolicyPath
		if !filepath.IsAbs(policyPath) {
			policyPath = filepath.Join(repoPath, filepath.FromSlash(policyPath))
		}
		args = append(args, "--policy", policyPath)
	}

	stdout, stderr, runErr := runCommand(ctx, repoPath, nil, service.cfg.CVEFixBinary, args...)
	exitCode := commandExitCode(runErr)
	if runErr != nil && exitCode != 23 {
		return fixRunResult{}, fmt.Errorf("run cvefix (exit %d): %w\nstderr:\n%s", exitCode, runErr, truncateForComment(stderr))
	}

	changed, err := hasRepositoryChanges(ctx, repoPath)
	if err != nil {
		return fixRunResult{}, err
	}
	if !changed {
		return fixRunResult{ExitCode: exitCode, Stdout: stdout, Stderr: stderr, Changed: false}, nil
	}

	branch := fmt.Sprintf("patchpilot/auto-fix-%s", time.Now().UTC().Format("20060102-150405"))
	if _, _, err := runCommand(ctx, repoPath, nil, "git", "checkout", "-b", branch); err != nil {
		return fixRunResult{}, fmt.Errorf("create branch: %w", err)
	}
	if _, _, err := runCommand(ctx, repoPath, nil, "git", "add", "-A"); err != nil {
		return fixRunResult{}, fmt.Errorf("git add: %w", err)
	}

	commitEnv := map[string]string{
		"GIT_AUTHOR_NAME":     "patchpilot-app[bot]",
		"GIT_AUTHOR_EMAIL":    "patchpilot-app[bot]@users.noreply.github.com",
		"GIT_COMMITTER_NAME":  "patchpilot-app[bot]",
		"GIT_COMMITTER_EMAIL": "patchpilot-app[bot]@users.noreply.github.com",
	}
	if _, _, err := runCommand(ctx, repoPath, commitEnv, "git", "commit", "-m", "chore: automated CVE remediation"); err != nil {
		if !strings.Contains(err.Error(), "nothing to commit") {
			return fixRunResult{}, fmt.Errorf("git commit: %w", err)
		}
	}

	if _, _, err := runCommand(ctx, repoPath, nil, "git", "push", "origin", branch); err != nil {
		return fixRunResult{}, fmt.Errorf("git push: %w", err)
	}

	return fixRunResult{
		ExitCode: exitCode,
		Stdout:   stdout,
		Stderr:   stderr,
		Changed:  true,
		Branch:   branch,
	}, nil
}

func (service *Service) postIssueComment(ctx context.Context, client *github.Client, owner, repo string, issueNumber int, body string) {
	if strings.TrimSpace(body) == "" {
		return
	}
	if _, _, err := client.Issues.CreateComment(ctx, owner, repo, issueNumber, &github.IssueComment{Body: github.String(body)}); err != nil {
		service.logger.Printf("post issue comment failed for %s/%s#%d: %v", owner, repo, issueNumber, err)
	}
}

func runCommand(ctx context.Context, dir string, extraEnv map[string]string, name string, args ...string) (string, string, error) {
	if err := validateExecutableName(name); err != nil {
		return "", "", err
	}

	command := exec.CommandContext(ctx, name, args...) // #nosec G204,G702 -- command/args are controlled by internal callsites and validated executable names.
	command.Dir = dir

	if len(extraEnv) > 0 {
		env := os.Environ()
		for key, value := range extraEnv {
			env = append(env, key+"="+value)
		}
		command.Env = env
	}

	var stdoutBuffer bytes.Buffer
	var stderrBuffer bytes.Buffer
	command.Stdout = &stdoutBuffer
	command.Stderr = &stderrBuffer

	err := command.Run()
	return stdoutBuffer.String(), stderrBuffer.String(), err
}

func validateExecutableName(name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return fmt.Errorf("command name cannot be empty")
	}
	if strings.ContainsAny(name, "\n\r\t") {
		return fmt.Errorf("command name contains invalid characters")
	}
	return nil
}

func hasRepositoryChanges(ctx context.Context, repoPath string) (bool, error) {
	stdout, _, err := runCommand(ctx, repoPath, nil, "git", "status", "--porcelain")
	if err != nil {
		return false, fmt.Errorf("check git status: %w", err)
	}
	return strings.TrimSpace(stdout) != "", nil
}

func commandExitCode(err error) int {
	if err == nil {
		return 0
	}
	var exitErr *exec.ExitError
	if errors.As(err, &exitErr) {
		return exitErr.ExitCode()
	}
	return -1
}

func truncateForComment(text string) string {
	trimmed := strings.TrimSpace(text)
	if trimmed == "" {
		return "(empty)"
	}
	const max = 3500
	if len(trimmed) <= max {
		return trimmed
	}
	return trimmed[:max] + "\n... (truncated)"
}
