package githubapp

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/google/go-github/v75/github"
)

func (service *Service) remediationPRBody(trigger, command string, result fixRunResult) string {
	return fmt.Sprintf(
		"Automated remediation generated by PatchPilot App.\n\n- Trigger: %s\n- Command: `%s`\n- PatchPilot exit code: `%d`\n- Risk score: `%d`\n- Changed files: `%d`\n- Validation: deferred to pull request CI\n\nStdout (truncated):\n```text\n%s\n```\n\nStderr (truncated):\n```text\n%s\n```",
		trigger,
		command,
		result.ExitCode,
		result.RiskScore,
		len(result.ChangedFiles),
		truncateForComment(result.Stdout),
		truncateForComment(result.Stderr),
	)
}

func (service *Service) findOpenRemediationPR(ctx context.Context, client *github.Client, owner, repo, baseBranch string) (*github.PullRequest, bool, error) {
	options := &github.PullRequestListOptions{
		State: "open",
		Base:  baseBranch,
		ListOptions: github.ListOptions{
			PerPage: 100,
		},
	}
	var prs []*github.PullRequest
	err := service.withGitHubRetry(ctx, "list_pull_requests", func(callCtx context.Context) error {
		response, _, listErr := client.PullRequests.List(callCtx, owner, repo, options)
		if listErr != nil {
			return listErr
		}
		prs = response
		return nil
	})
	if err != nil {
		return nil, false, err
	}
	for _, pr := range prs {
		if pr.GetTitle() != remediationPRTitle {
			continue
		}
		ref := pr.GetHead().GetRef()
		if strings.HasPrefix(ref, "patchpilot/auto-fix-") {
			return pr, true, nil
		}
	}
	return nil, false, nil
}

func (service *Service) upsertRemediationPR(ctx context.Context, client *github.Client, owner, repo, baseBranch, headBranch, body string, existing *github.PullRequest) (*github.PullRequest, bool, error) {
	if existing != nil {
		var updated *github.PullRequest
		err := service.withGitHubRetry(ctx, "edit_pull_request", func(callCtx context.Context) error {
			response, _, editErr := client.PullRequests.Edit(callCtx, owner, repo, existing.GetNumber(), &github.PullRequest{
				Title: github.Ptr(remediationPRTitle),
				Body:  github.Ptr(body),
			})
			if editErr != nil {
				return editErr
			}
			updated = response
			return nil
		})
		if err != nil {
			return nil, false, err
		}
		return updated, false, nil
	}
	var created *github.PullRequest
	err := service.withGitHubRetry(ctx, "create_pull_request", func(callCtx context.Context) error {
		response, _, createErr := client.PullRequests.Create(callCtx, owner, repo, &github.NewPullRequest{
			Title: github.Ptr(remediationPRTitle),
			Head:  github.Ptr(headBranch),
			Base:  github.Ptr(baseBranch),
			Body:  github.Ptr(body),
		})
		if createErr != nil {
			return createErr
		}
		created = response
		return nil
	})
	if err != nil {
		return nil, false, err
	}
	return created, true, nil
}

func (service *Service) closeRemediationPullRequest(ctx context.Context, client *github.Client, owner, repo, repoKey string, pr *github.PullRequest, assessment ciAssessment, evidence []ciLogEvidence, now time.Time) error {
	commentBody := buildClosedPRComment(assessment, evidence)
	commentURL, err := service.createPullRequestComment(ctx, client, owner, repo, pr.GetNumber(), commentBody)
	if err != nil {
		return err
	}
	if err := service.withGitHubRetry(ctx, "close_pull_request", func(callCtx context.Context) error {
		_, _, closeErr := client.PullRequests.Edit(callCtx, owner, repo, pr.GetNumber(), &github.PullRequest{
			State: github.Ptr("closed"),
		})
		return closeErr
	}); err != nil {
		return err
	}
	if err := service.deleteBranch(ctx, client, owner, repo, pr.GetHead().GetRef()); err != nil {
		return err
	}
	return service.updateRepositoryState(repoKey, func(state *scheduledRepositoryState) {
		if state.OpenPR != nil {
			state.OpenPR.LastClosureComment = commentURL
		}
		state.OpenPR = nil
	}, now)
}

func (service *Service) createPullRequestComment(ctx context.Context, client *github.Client, owner, repo string, prNumber int, body string) (string, error) {
	var comment *github.IssueComment
	err := service.withGitHubRetry(ctx, "create_issue_comment", func(callCtx context.Context) error {
		var commentErr error
		comment, _, commentErr = client.Issues.CreateComment(callCtx, owner, repo, prNumber, &github.IssueComment{
			Body: github.Ptr(body),
		})
		return commentErr
	})
	if err != nil {
		return "", err
	}
	return comment.GetHTMLURL(), nil
}

func (service *Service) deleteBranch(ctx context.Context, client *github.Client, owner, repo, branch string) error {
	branch = strings.TrimSpace(branch)
	if branch == "" {
		return nil
	}
	return service.withGitHubRetry(ctx, "delete_git_ref", func(callCtx context.Context) error {
		_, deleteErr := client.Git.DeleteRef(callCtx, owner, repo, "heads/"+branch)
		return deleteErr
	})
}

func buildClosedPRComment(assessment ciAssessment, evidence []ciLogEvidence) string {
	var builder strings.Builder
	builder.WriteString("PatchPilot closed this remediation PR after exhausting CI repair attempts.\n\n")
	builder.WriteString("- Classification: " + assessment.Classification + "\n")
	if strings.TrimSpace(assessment.Summary) != "" {
		builder.WriteString("- Summary: " + assessment.Summary + "\n")
	}
	if len(evidence) > 0 {
		builder.WriteString("\nFailed CI evidence (truncated):\n")
		for _, item := range evidence {
			builder.WriteString("\n```text\n")
			builder.WriteString(item.Name)
			builder.WriteString("\n")
			builder.WriteString(truncateForComment(item.Log))
			builder.WriteString("\n```\n")
		}
	}
	return builder.String()
}

func (service *Service) enablePRAutoMerge(ctx context.Context, installationToken, pullRequestNodeID string) error {
	if strings.TrimSpace(installationToken) == "" {
		return fmt.Errorf("installation token is empty")
	}
	if strings.TrimSpace(pullRequestNodeID) == "" {
		return fmt.Errorf("pull request node ID is empty")
	}

	graphqlURL, err := service.graphqlURL()
	if err != nil {
		return err
	}

	payload := map[string]interface{}{
		"query": `mutation EnableAutoMerge($pullRequestId: ID!) { enablePullRequestAutoMerge(input: {pullRequestId: $pullRequestId, mergeMethod: SQUASH}) { pullRequest { id } } }`,
		"variables": map[string]string{
			"pullRequestId": pullRequestNodeID,
		},
	}
	data, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("marshal graphql payload: %w", err)
	}

	request, err := http.NewRequestWithContext(ctx, http.MethodPost, graphqlURL, bytes.NewReader(data))
	if err != nil {
		return fmt.Errorf("create graphql request: %w", err)
	}
	request.Header.Set("Authorization", "Bearer "+installationToken)
	request.Header.Set("Content-Type", "application/json")

	return service.withGitHubRetry(ctx, "enable_pr_auto_merge", func(callCtx context.Context) error {
		retryRequest := request.Clone(callCtx)
		retryRequest.Body = io.NopCloser(bytes.NewReader(data))
		response, reqErr := http.DefaultClient.Do(retryRequest)
		if reqErr != nil {
			return reqErr
		}
		defer func() {
			_ = response.Body.Close()
		}()

		if response.StatusCode < 300 {
			return nil
		}
		bodyBytes, _ := io.ReadAll(io.LimitReader(response.Body, 4096))
		return &httpStatusError{
			StatusCode: response.StatusCode,
			Header:     response.Header.Clone(),
			Body:       string(bodyBytes),
		}
	})
}

func (service *Service) graphqlURL() (string, error) {
	baseURL := strings.TrimSpace(service.cfg.GitHubAPIBaseURL)
	if baseURL == "" {
		return "https://api.github.com/graphql", nil
	}
	parsed, err := url.Parse(baseURL)
	if err != nil {
		return "", fmt.Errorf("parse github api base URL: %w", err)
	}
	cleanPath := strings.TrimSuffix(parsed.Path, "/")
	cleanPath = strings.TrimSuffix(cleanPath, "/api/v3")
	parsed.Path = cleanPath + "/api/graphql"
	parsed.RawQuery = ""
	parsed.Fragment = ""
	return parsed.String(), nil
}
