oci:
  mappings:
    - repo: external-secrets/external-secrets
      images:
        - source: ghcr.io/external-secrets/external-secrets
          dockerfiles:
            - Dockerfile
          tag: latest-semver
